# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio_proveedor', models.FloatField(default=0.0)),
                ('precio_venta', models.FloatField(default=0.0)),
                ('precio_anterior_venta', models.FloatField(default=0.0)),
                ('existencia', models.FloatField(default=0.0, verbose_name='en stock')),
                ('descripcion', models.CharField(max_length=500)),
                ('caracteristicasTecnica', models.CharField(max_length=10000)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('modelo', models.CharField(max_length=200)),
                ('estado', models.IntegerField(choices=[(1, 'PENDIENTE'), (2, 'EN VERIFICACION'), (3, 'PUBLICADO'), (4, 'DESHABILITADO')], default=1)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('plantilla', models.CharField(default='home/product2.html', max_length=500)),
                ('especial', models.BooleanField(default=False)),
            ],
        ),
    ]
