# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=100)),
                ('column2', models.CharField(max_length=100)),
                ('column3', models.CharField(max_length=100)),
                ('column4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(max_length=100)),
                ('column2', models.CharField(max_length=100)),
                ('column3', models.CharField(max_length=100)),
                ('column4', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.Master'),
        ),
    ]
